# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ga4ghtest.models.base_model_ import Model
from ga4ghtest import util


class Plugin(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, version=None, apis=None, recipe=None):  # noqa: E501
        """Plugin - a model defined in OpenAPI

        :param id: The id of this Plugin.  # noqa: E501
        :type id: str
        :param name: The name of this Plugin.  # noqa: E501
        :type name: str
        :param version: The version of this Plugin.  # noqa: E501
        :type version: str
        :param apis: The apis of this Plugin.  # noqa: E501
        :type apis: List[str]
        :param recipe: The recipe of this Plugin.  # noqa: E501
        :type recipe: str
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'version': str,
            'apis': List[str],
            'recipe': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'version': 'version',
            'apis': 'apis',
            'recipe': 'recipe'
        }

        self._id = id
        self._name = name
        self._version = version
        self._apis = apis
        self._recipe = recipe

    @classmethod
    def from_dict(cls, dikt) -> 'Plugin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Plugin of this Plugin.  # noqa: E501
        :rtype: Plugin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Plugin.


        :return: The id of this Plugin.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Plugin.


        :param id: The id of this Plugin.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Plugin.


        :return: The name of this Plugin.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Plugin.


        :param name: The name of this Plugin.
        :type name: str
        """

        self._name = name

    @property
    def version(self):
        """Gets the version of this Plugin.


        :return: The version of this Plugin.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Plugin.


        :param version: The version of this Plugin.
        :type version: str
        """

        self._version = version

    @property
    def apis(self):
        """Gets the apis of this Plugin.


        :return: The apis of this Plugin.
        :rtype: List[str]
        """
        return self._apis

    @apis.setter
    def apis(self, apis):
        """Sets the apis of this Plugin.


        :param apis: The apis of this Plugin.
        :type apis: List[str]
        """
        allowed_values = ["WES", "TRS"]  # noqa: E501
        if not set(apis).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `apis` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(apis) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._apis = apis

    @property
    def recipe(self):
        """Gets the recipe of this Plugin.


        :return: The recipe of this Plugin.
        :rtype: str
        """
        return self._recipe

    @recipe.setter
    def recipe(self, recipe):
        """Sets the recipe of this Plugin.


        :param recipe: The recipe of this Plugin.
        :type recipe: str
        """

        self._recipe = recipe
