# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ga4ghtest.models.base_model_ import Model
from ga4ghtest.openapi import util


class RequestRecipe(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, request=None, response=None):  # noqa: E501
        """RequestRecipe - a model defined in OpenAPI

        :param request: The request of this RequestRecipe.  # noqa: E501
        :type request: str
        :param response: The response of this RequestRecipe.  # noqa: E501
        :type response: str
        """
        self.openapi_types = {
            'request': str,
            'response': str
        }

        self.attribute_map = {
            'request': 'request',
            'response': 'response'
        }

        self._request = request
        self._response = response

    @classmethod
    def from_dict(cls, dikt) -> 'RequestRecipe':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestRecipe of this RequestRecipe.  # noqa: E501
        :rtype: RequestRecipe
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request(self):
        """Gets the request of this RequestRecipe.


        :return: The request of this RequestRecipe.
        :rtype: str
        """
        return self._request

    @request.setter
    def request(self, request):
        """Sets the request of this RequestRecipe.


        :param request: The request of this RequestRecipe.
        :type request: str
        """

        self._request = request

    @property
    def response(self):
        """Gets the response of this RequestRecipe.


        :return: The response of this RequestRecipe.
        :rtype: str
        """
        return self._response

    @response.setter
    def response(self, response):
        """Sets the response of this RequestRecipe.


        :param response: The response of this RequestRecipe.
        :type response: str
        """

        self._response = response
