# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ga4ghtest.models.base_model_ import Model
from ga4ghtest.openapi import util


class ServiceTest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, servers=None, plugin=None):  # noqa: E501
        """ServiceTest - a model defined in OpenAPI

        :param servers: The servers of this ServiceTest.  # noqa: E501
        :type servers: List[str]
        :param plugin: The plugin of this ServiceTest.  # noqa: E501
        :type plugin: str
        """
        self.openapi_types = {
            'servers': List[str],
            'plugin': str
        }

        self.attribute_map = {
            'servers': 'servers',
            'plugin': 'plugin'
        }

        self._servers = servers
        self._plugin = plugin

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceTest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceTest of this ServiceTest.  # noqa: E501
        :rtype: ServiceTest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def servers(self):
        """Gets the servers of this ServiceTest.


        :return: The servers of this ServiceTest.
        :rtype: List[str]
        """
        return self._servers

    @servers.setter
    def servers(self, servers):
        """Sets the servers of this ServiceTest.


        :param servers: The servers of this ServiceTest.
        :type servers: List[str]
        """

        self._servers = servers

    @property
    def plugin(self):
        """Gets the plugin of this ServiceTest.


        :return: The plugin of this ServiceTest.
        :rtype: str
        """
        return self._plugin

    @plugin.setter
    def plugin(self, plugin):
        """Sets the plugin of this ServiceTest.


        :param plugin: The plugin of this ServiceTest.
        :type plugin: str
        """

        self._plugin = plugin
